site_name: Halima's SOC Learning Journal
site_description: Blue Team learning in public — SOC fundamentals, labs, and writeups
site_author: Hal Abdi

theme:
  name: material
  palette:
    - scheme: default
      primary: black
      accent: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.top
    - search.suggest

nav:
  - Home: index.md
  - Week 01:
    - Notes: week-01/notes.md
    - Lab Writeup: week-01/lab-writeup.md
    - Diagrams: week-01/diagrams/diagrams.md
  - Week 02:
    - Notes: week-02/notes.md
  - Week 03:
    - Notes: week-03/notes.md

plugins:
  - search
